variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image: jojomi/hugo:0.36
  stage: build
  script:
    - sed -i "s|baseURL.*|baseURL = \"$deploy_url/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME\"|" config.toml
    - sed -i "s|editURL.*|editURL = \"$gitlab_url/$CI_PROJECT_PATH/edit/$CI_COMMIT_REF_NAME/content/\"|" config.toml
    - sed -i '/<title>/d' themes/docdock/layouts/_default/baseof.html
    - cat config.toml
    - hugo
  artifacts:
    paths:
      - public
    expire_in: 1 day

ide-build:
  image: jojomi/hugo:0.36
  stage: build
  script:
    - apk add --no-cache zip
    - sed -i "s|<a href=\"{{ .RelPermalink}}\"|<a href=\"{{ .RelPermalink}}index.html\"|g" themes/docdock/layouts/partials/menu.html
    - sed -i "s|.Page -}}|.Page -}}index.html|g" themes/docdock/layouts/shortcodes/relref.html
    - sed -i "s|URL -}}|URL -}}index.html|g" themes/docdock/layouts/shortcodes/relref.html
    - sed -i "s|URL}}|URL}}index.html|g" themes/docdock/layouts/shortcodes/children.html
    - sed -i '/<title>/d' themes/docdock/layouts/_default/baseof.html
    - sed -i "s|disableSearch = false|disableSearch = true|g" config.toml
    - sed -i "s|disableHomeIcon = false|disableHomeIcon = true|g" config.toml
    - sed -i "s|disableNavChevron = false|disableNavChevron = true|g" config.toml
    - sed -i "s|editURL|#editURL|g" config.toml
    - hugo
    - mv public html
    - zip -r redhawksdr-org.zip html
  artifacts:
    paths:
      - redhawksdr-org.zip
    expire_in: 1 day

deploy:
  image: ${docker_registry}redhawk/deploy:latest
  stage: deploy
  dependencies:
    - build
    - ide-build
  tags:
    - deployment
  script:
    - eval "$(ssh-agent -s)"
    - ssh-add
    - mkdir -p $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
    - mv ../public $CI_COMMIT_REF_NAME
    - mv ../redhawksdr-org.zip $CI_COMMIT_REF_NAME
    - rsync -avzP --delete $CI_COMMIT_REF_NAME $PUBLISH_URL:$PUBLISH_PATH/$CI_PROJECT_NAME
    #Trigger redhawk website build
    - curl --insecure -X POST
                      -F ref=master
                      -F token=$token
                      $gitlab_url/api/v4/projects/$CI_PROJECT_NAMESPACE%2F$CI_PROJECT_NAME/trigger/pipeline
